# Generated by Django 5.2.7 on 2025-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_alter_employee_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
